### ISSUE TITLE
Importing a task fails with an exception

### ISSUE THREAD

**Issue by dbogdanov** [matt-snider/todoist-taskwarrior#2]
The error message:

```
Traceback (most recent call last):
  File "/home/dbogdanov/install/todoist-taskwarrior/todoist_taskwarrior/io.py", line 57, in with_feedback
    yield
  File "/home/dbogdanov/install/todoist-taskwarrior/todoist_taskwarrior/cli.py", line 178, in add_task
    todoist_id=tid,
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/taskw/warrior.py", line 683, in task_add
    stdout, stderr = self._execute('add', *args)
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/taskw/warrior.py", line 476, in _execute
    raise TaskwarriorError(command, stderr, stdout, proc.returncode)
taskw.exceptions.TaskwarriorError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dbogdanov/install/todoist-taskwarrior/todoist_taskwarrior/cli.py", line 311, in <module>
    cli()
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dbogdanov/.local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dbogdanov/install/todoist-taskwarrior/todoist_taskwarrior/cli.py", line 153, in migrate
    add_task(**data)
  File "/home/dbogdanov/install/todoist-taskwarrior/todoist_taskwarrior/cli.py", line 178, in add_task
    todoist_id=tid,
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dbogdanov/install/todoist-taskwarrior/todoist_taskwarrior/io.py", line 59, in with_feedback
    error(f'{error_status} ({e})')
TypeError: __str__ returned non-string (type bytes)
```

**Comment by matt-snider** [comment]
Hi @dbogdanov thanks for the bug report.

Interesting - it seems like both the inner and outer exceptions relate to str errors, potentially something with encoding. Did you run the tool in interactive mode? If not could you run it in interactive mode and post any relevant info about the task that is being imported? It would be good to see what data the input task contains. You can of course omit anything sensitive

**Comment by davidgasquez** [comment]
Just installed it and I'm having the same issue! Would you mind sharing how can I run the tool in interactive mode @matt-snider? Would love to help in any way I can.

**Comment by dbogdanov** [comment]
Use ```-i``` flag for interactive mode.

**Comment by davidgasquez** [comment]
Just realized that I'm using [`webmeisterei/todoist-taskwarrior`](https://git.webmeisterei.com/webmeisterei/todoist-taskwarrior/), I don't have that `-i` flag. If @dbogdanov isn't able to provide the logs I'll install this tool and run it with `-i`.

**Comment by dbogdanov** [comment]
Please, do so. I could not narrow down the reason, except for that I assume the issue is with tags (setting `tags=[]` in [cli.py](https://github.com/matt-snider/todoist-taskwarrior/blob/master/todoist_taskwarrior/cli.py#L173) fixed the problem for all imported tasks).

**Comment by davidgasquez** [comment]
This is what I'm getting:

```
❯ venv/bin/python -m todoist_taskwarrior.cli migrate --interactive
Syncing tasks with todoist... OK
Starting migration of 29 tasks...
Task 1 of 29: Welcome to Todoist 👋 Let’s get you started with a few tips:
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/david/projects/todoist-taskwarrior/todoist_taskwarrior/cli.py", line 311, in <module>
    cli()
  File "/home/david/projects/todoist-taskwarrior/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/projects/todoist-taskwarrior/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/david/projects/todoist-taskwarrior/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/david/projects/todoist-taskwarrior/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/projects/todoist-taskwarrior/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/david/projects/todoist-taskwarrior/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/david/projects/todoist-taskwarrior/todoist_taskwarrior/cli.py", line 127, in migrate
    while p['parent_id']:
TypeError: 'NoneType' object is not subscriptable

```

**Comment by matt-snider** [comment]
@davidgasquez That looks to be a different error than the one reported by @dbogdanov . It seems like it's failing when trying to get the project associated with the task.

I just pushed some changes that add debug logging and a new option to allow running with a different taskrc file. This makes it easy to run the migration with `sandbox/` as the target, to prevent clobbering the global taskwarrior data while debugging.

Could you please pull my changes and run the following:
```sh
python -m todoist_taskwarrior.cli \
    --debug \
    --tw-config-file=./sandbox/.taskrc \
    migrate \
    --no-sync \
    -i
```

Take a look at the output and paste it here (omitting of course any private details from the task data).

**Comment by davidgasquez** [comment]
Sure @matt-snider! This is what I'm getting :) 

https://pastebin.com/fWqUYbci

**Comment by matt-snider** [comment]
@davidgasquez Ok, I see the issue. Todoist can have tasks with no project. I just pushed a simple change that should fix it. Could you pull and run the tool again and see if it works?

**Comment by davidgasquez** [comment]
Hey there! Pulled the change but I'm still seeing the same error. :confused: 

https://pastebin.com/HUjh9vxx

**Comment by matt-snider** [comment]
@davidgasquez It's strange, but that first task has a `project_id` but no project is found. I'm not sure why that would be, but the change I just pushed should let the migration continue with a warning. Hopefully it works this time :sweat_smile:

**Comment by davidgasquez** [comment]
Thanks @matt-snider! Its working now. I appreciate your help here! :raised_hands:

**Comment by matt-snider** [comment]
@davidgasquez Glad to hear it! Just a reminder to remove the sandboxing flag (if you haven't already) once you are ready to migrate into your actual taskwarrior data dir.


@dbogdanov The issue you had appears to be different. Could you pull and try running it again?

**Comment by dbogdanov** [comment]
@matt-snider Is that possible to add an option to import a specific task ID? This way I will be able to synthesize a good example.

**Comment by matt-snider** [comment]
@dbogdanov That's a good idea and was easy to implement. You can use `--filter-task-id=<my-task-id>` or `--filter-proj-id=<my-proj-id>`.

Can you pull and give it a shot?
